export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const GET_SINGER = 'GET_SINGER';
export const SINGER_LOADING = 'SINGER_LOADING';
export const SINGER_NOT_FOUND = 'SINGER_NOT_FOUND';
export const CLEAR_CURRENT_SINGER = 'CLEAR_CURRENT_SINGER';
export const GET_SINGERS = 'GET_SINGERS';